import { NodeLabel, TechTree, InvestTechTreeGraph } from './lib/types';

const tech_tree: InvestTechTreeGraph = {
  nodes: [
    {
      id: 'concept_lts_tokamak',
      label: 'LTS Tokamak',
      type: 'ReactorConcept',
      category: 'Fusion',
      trl_current: '5-6',
    },
    {
      id: 'milestone_lts_physics_validation',
      label: 'LTS Tokamak Physics Validation',
      type: 'Milestone',
      subtype: 'PhysicsDemonstration',
      trl_current: '5',
    },
    {
      id: 'milestone_iter_construction',
      label: 'ITER Burning Plasma Demo',
      type: 'Milestone',
      subtype: 'PrototypeConstruction',
      trl_current: '5-6',
    },
    {
      id: 'concept_hts_tokamak',
      label: 'HTS Tokamak',
      type: 'ReactorConcept',
      category: 'Fusion',
      trl_current: '4-5',
    },
    {
      id: 'milestone_hts_magnet_demo',
      label: 'Large-Scale HTS Magnet Demo',
      type: 'Milestone',
      subtype: 'ComponentTest',
      trl_current: '4-5',
    },
    {
      id: 'milestone_sparc_net_energy',
      label: 'SPARC Net Energy Demo',
      type: 'Milestone',
      subtype: 'PrototypeConstruction',
      trl_current: '4',
      trl_projected_5_10_years: '6',
    },
    {
      id: 'concept_stellarator',
      label: 'Stellarator',
      type: 'ReactorConcept',
      category: 'Fusion',
      trl_current: '4-5',
    },
    {
      id: 'milestone_w7x_optimization_proof',
      label: 'W7-X Optimized Physics Proof',
      type: 'Milestone',
      subtype: 'PhysicsDemonstration',
      trl_current: '4-5',
    },
    {
      id: 'milestone_hts_stellarator_coil_fab',
      label: 'HTS Stellarator Coil Fabrication',
      type: 'Milestone',
      subtype: 'ComponentTest',
      trl_current: '2-3',
      trl_projected_5_10_years: '4',
    },
    {
      id: 'concept_frc',
      label: 'Field-Reversed Configuration',
      type: 'ReactorConcept',
      category: 'Fusion',
      trl_current: '4',
    },
    {
      id: 'milestone_frc_stable_sustainment',
      label: 'FRC Stable Sustainment',
      type: 'Milestone',
      subtype: 'PhysicsDemonstration',
      trl_current: '4',
    },
    {
      id: 'milestone_frc_net_energy',
      label: 'FRC Net Energy Demo',
      type: 'Milestone',
      subtype: 'PrototypeConstruction',
      trl_current: '3',
      trl_projected_5_10_years: '5',
    },
    {
      id: 'concept_icf',
      label: 'Inertial Confinement Fusion',
      type: 'ReactorConcept',
      category: 'Fusion',
      trl_current: '2-3',
    },
    {
      id: 'milestone_nif_ignition',
      label: 'NIF Single-Shot Ignition',
      type: 'Milestone',
      subtype: 'PhysicsDemonstration',
      trl_current: '5-6',
    },
    {
      id: 'milestone_ife_driver_dev',
      label: 'IFE High-Rep-Rate Driver',
      type: 'Milestone',
      subtype: 'ComponentDevelopment',
      trl_current: '2-3',
      trl_projected_5_10_years: '4-5',
    },
    {
      id: 'concept_z_pinch',
      label: 'Z-Pinch',
      type: 'ReactorConcept',
      category: 'Fusion',
      trl_current: '4',
    },
    {
      id: 'milestone_sfs_z_pinch_stability',
      label: 'Sheared-Flow Z-Pinch Stability',
      type: 'Milestone',
      subtype: 'PhysicsDemonstration',
      trl_current: '4',
    },
    {
      id: 'concept_lwr_smr',
      label: 'Light Water SMR',
      type: 'ReactorConcept',
      category: 'Fission',
      trl_current: '7-8',
    },
    {
      id: 'milestone_lwr_smr_design_approval',
      label: 'SMR Standard Design Approval',
      type: 'Milestone',
      subtype: 'Regulatory',
      trl_current: '7-8',
    },
    {
      id: 'milestone_lwr_smr_first_build',
      label: 'First Commercial SMR Build',
      type: 'Milestone',
      subtype: 'CommercialDeployment',
      trl_current: '7',
      trl_projected_5_10_years: '9',
    },
    {
      id: 'concept_htgr',
      label: 'High-Temp Gas Reactor',
      type: 'ReactorConcept',
      category: 'Fission',
      trl_current: '6-7',
    },
    {
      id: 'milestone_htgr_demo_reactors',
      label: 'HTGR Demo Reactor Operation',
      type: 'Milestone',
      subtype: 'PrototypeDemonstration',
      trl_current: '6-7',
    },
    {
      id: 'concept_msr',
      label: 'Molten Salt Reactor',
      type: 'ReactorConcept',
      category: 'Fission',
      trl_current: '3-4',
    },
    {
      id: 'milestone_msre_operation',
      label: 'MSRE Proof-of-Concept',
      type: 'Milestone',
      subtype: 'PhysicsDemonstration',
      trl_current: '4',
    },
    {
      id: 'milestone_msr_materials_qualification',
      label: 'MSR Materials & Chemistry Control',
      type: 'Milestone',
      subtype: 'ComponentDevelopment',
      trl_current: '3-4',
      trl_projected_5_10_years: '5-6',
    },
    {
      id: 'concept_sfr',
      label: 'Sodium-Cooled Fast Reactor',
      type: 'ReactorConcept',
      category: 'Fission',
      trl_current: '5-6',
    },
    {
      id: 'milestone_sfr_prototype_operation',
      label: 'SFR Prototype Reactor Operation',
      type: 'Milestone',
      subtype: 'PrototypeDemonstration',
      trl_current: '5-6',
    },
    {
      id: 'concept_lfr',
      label: 'Lead-Cooled Fast Reactor',
      type: 'ReactorConcept',
      category: 'Fission',
      trl_current: '3-4',
    },
    {
      id: 'milestone_lfr_materials_qualification',
      label: 'LFR Materials Qualification',
      type: 'Milestone',
      subtype: 'ComponentDevelopment',
      trl_current: '3-4',
      trl_projected_5_10_years: '5',
    },
    {
      id: 'concept_twr',
      label: 'Traveling Wave Reactor',
      type: 'ReactorConcept',
      category: 'Fission',
      trl_current: '2-3',
    },
    {
      id: 'milestone_twr_fuel_qualification',
      label: 'TWR Extreme-Burnup Fuel',
      type: 'Milestone',
      subtype: 'ComponentDevelopment',
      trl_current: '2-3',
    },
    {
      id: 'tech_hts_magnets',
      label: 'HTS Magnets',
      type: 'EnablingTechnology',
      trl_current: '4-5 (Tokamaks); 2-3 (Stellarators)',
    },
    {
      id: 'tech_triso_fuel',
      label: 'TRISO Fuel Cycle',
      type: 'EnablingTechnology',
      trl_current: '7-8 (Fabrication); 2-3 (Processing)',
    },
    {
      id: 'tech_metallic_fuel',
      label: 'Metallic Fuel Cycle',
      type: 'EnablingTechnology',
      trl_current: '6-7',
    },
    {
      id: 'tech_tritium_breeding',
      label: 'Tritium Breeding Blankets',
      type: 'EnablingTechnology',
      trl_current: '3-4',
    },
    {
      id: 'tech_pfm',
      label: 'Plasma-Facing Materials',
      type: 'EnablingTechnology',
      trl_current: '3-4',
    },
    {
      id: 'tech_haleu',
      label: 'HALEU Fuel Supply',
      type: 'EnablingTechnology',
      trl_current: '3-4 (Production)',
    },
    {
      id: 'tech_power_cycle_sco2',
      label: 'sCO2 Power Cycle',
      type: 'EnablingTechnology',
      trl_current: '5-6',
    },
    {
      id: 'milestone_step_demo_operation',
      label: 'STEP sCO2 Demo Plant Operation',
      type: 'Milestone',
      subtype: 'PrototypeDemonstration',
      trl_current: '6',
    },
    {
      id: 'tech_ai_ml_control',
      label: 'AI/ML for Control & Design',
      type: 'EnablingTechnology',
      trl_current: '3-5',
    },
    {
      id: 'tech_passive_safety',
      label: 'Passive Safety Systems',
      type: 'EnablingTechnology',
      trl_current: '7-9 (LWRs); 4-6 (Novel Coolants)',
    },
    {
      id: 'tech_rad_hard_electronics',
      label: 'Radiation-Hardened Electronics',
      type: 'EnablingTechnology',
      trl_current: '3-7 (Application Dependent)',
    },
    {
      id: 'tech_plasma_heating',
      label: 'Plasma Heating Systems',
      type: 'EnablingTechnology',
      trl_current: '5-6',
    },
    {
      id: 'tech_divertor_concepts',
      label: 'Advanced Divertor Concepts',
      type: 'EnablingTechnology',
      trl_current: '2-3',
    },
    {
      id: 'milestone_advanced_divertor_test',
      label: 'Advanced Divertor Test Facility (DTT)',
      type: 'Milestone',
      subtype: 'ComponentTest',
      trl_current: '3',
    },
  ],
  edges: [
    {
      id: 'dep_lts_physics_to_iter',
      source: 'milestone_lts_physics_validation',
      target: 'milestone_iter_construction',
    },
    {
      id: 'dep_iter_to_tbm_test',
      source: 'milestone_iter_construction',
      target: 'tech_tritium_breeding',
    },
    {
      id: 'dep_iter_to_pfm_test',
      source: 'milestone_iter_construction',
      target: 'tech_pfm',
    },
    {
      id: 'dep_hts_tech_to_magnet_demo',
      source: 'tech_hts_magnets',
      target: 'milestone_hts_magnet_demo',
    },
    {
      id: 'dep_magnet_demo_to_sparc',
      source: 'milestone_hts_magnet_demo',
      target: 'milestone_sparc_net_energy',
    },
    {
      id: 'dep_w7x_to_hts_stellarator',
      source: 'milestone_w7x_optimization_proof',
      target: 'milestone_hts_stellarator_coil_fab',
    },
    {
      id: 'dep_hts_tech_to_stellarator_fab',
      source: 'tech_hts_magnets',
      target: 'milestone_hts_stellarator_coil_fab',
    },
    {
      id: 'dep_frc_sustain_to_net_energy',
      source: 'milestone_frc_stable_sustainment',
      target: 'milestone_frc_net_energy',
    },
    {
      id: 'dep_nif_ignition_to_ife_driver',
      source: 'milestone_nif_ignition',
      target: 'milestone_ife_driver_dev',
    },
    {
      id: 'dep_lwr_smr_approval_to_build',
      source: 'milestone_lwr_smr_design_approval',
      target: 'milestone_lwr_smr_first_build',
    },
    {
      id: 'dep_triso_fab_to_htgr_demo',
      source: 'tech_triso_fuel',
      target: 'milestone_htgr_demo_reactors',
    },
    {
      id: 'dep_haleu_to_advanced_fission',
      source: 'tech_haleu',
      targets: ['concept_htgr', 'concept_sfr', 'concept_msr'],
    },
    {
      id: 'dep_msre_to_msr_materials',
      source: 'milestone_msre_operation',
      target: 'milestone_msr_materials_qualification',
    },
    {
      id: 'dep_sfr_proto_to_commercial',
      source: 'milestone_sfr_prototype_operation',
      target: 'concept_sfr',
    },
    {
      id: 'dep_metallic_fuel_to_fast_reactors',
      source: 'tech_metallic_fuel',
      targets: ['concept_sfr', 'concept_twr'],
    },
    {
      id: 'dep_sco2_tech_to_demo',
      source: 'tech_power_cycle_sco2',
      target: 'milestone_step_demo_operation',
    },
    {
      id: 'dep_sco2_demo_to_reactors',
      source: 'milestone_step_demo_operation',
      targets: ['concept_htgr', 'concept_sfr', 'concept_msr', 'concept_lfr'],
    },
    {
      id: 'dep_divertor_concepts_to_dtt',
      source: 'tech_divertor_concepts',
      target: 'milestone_advanced_divertor_test',
    },
    {
      id: 'dep_dtt_to_commercial_fusion',
      source: 'milestone_advanced_divertor_test',
      targets: ['concept_hts_tokamak', 'concept_stellarator'],
    },

    {
      id: 'link_iter_to_concept',
      source: 'milestone_iter_construction',
      target: 'concept_lts_tokamak',
    },
    {
      id: 'link_sparc_to_concept',
      source: 'milestone_sparc_net_energy',
      target: 'concept_hts_tokamak',
    },
    {
      id: 'link_hts_stellarator_to_concept',
      source: 'milestone_hts_stellarator_coil_fab',
      target: 'concept_stellarator',
    },
    {
      id: 'link_frc_to_concept',
      source: 'milestone_frc_net_energy',
      target: 'concept_frc',
    },
    {
      id: 'link_icf_to_concept',
      source: 'milestone_ife_driver_dev',
      target: 'concept_icf',
    },
    {
      id: 'link_z_pinch_to_concept',
      source: 'milestone_sfs_z_pinch_stability',
      target: 'concept_z_pinch',
    },
    {
      id: 'link_smr_to_concept',
      source: 'milestone_lwr_smr_first_build',
      target: 'concept_lwr_smr',
    },
    {
      id: 'link_htgr_to_concept',
      source: 'milestone_htgr_demo_reactors',
      target: 'concept_htgr',
    },
    {
      id: 'link_msr_to_concept',
      source: 'milestone_msr_materials_qualification',
      target: 'concept_msr',
    },
    {
      id: 'link_lfr_to_concept',
      source: 'milestone_lfr_materials_qualification',
      target: 'concept_lfr',
    },
    {
      id: 'link_twr_to_concept',
      source: 'milestone_twr_fuel_qualification',
      target: 'concept_twr',
    },

    {
      id: 'dep_tritium_to_fusion',
      source: 'tech_tritium_breeding',
      targets: [
        'concept_lts_tokamak',
        'concept_hts_tokamak',
        'concept_stellarator',
      ],
    },
    {
      id: 'dep_pfm_to_fusion',
      source: 'tech_pfm',
      targets: [
        'concept_lts_tokamak',
        'concept_hts_tokamak',
        'concept_stellarator',
        'concept_frc',
      ],
    },
    {
      id: 'dep_passive_safety_to_fission',
      source: 'tech_passive_safety',
      targets: [
        'concept_lwr_smr',
        'concept_htgr',
        'concept_msr',
        'concept_sfr',
        'concept_lfr',
      ],
    },
    {
      id: 'dep_rad_hard_to_all',
      source: 'tech_rad_hard_electronics',
      targets: [
        'concept_lts_tokamak',
        'concept_hts_tokamak',
        'concept_stellarator',
        'concept_frc',
        'concept_icf',
        'concept_z_pinch',
        'concept_lwr_smr',
        'concept_htgr',
        'concept_msr',
        'concept_sfr',
        'concept_lfr',
        'concept_twr',
      ],
    },
    {
      id: 'dep_plasma_heating_to_mcf',
      source: 'tech_plasma_heating',
      targets: [
        'concept_lts_tokamak',
        'concept_hts_tokamak',
        'concept_stellarator',
        'concept_frc',
      ],
    },
    {
      id: 'dep_ai_ml_to_all',
      source: 'tech_ai_ml_control',
      targets: [
        'concept_lts_tokamak',
        'concept_hts_tokamak',
        'concept_stellarator',
        'concept_frc',
        'concept_icf',
        'concept_z_pinch',
        'concept_lwr_smr',
        'concept_htgr',
        'concept_msr',
        'concept_sfr',
        'concept_lfr',
        'concept_twr',
      ],
    },
  ],
};

export const DATA: TechTree = {
  nodes: tech_tree.nodes.map((n) => ({
    id: n.id,
    data: {
      label: n.label,
      nodeLabel: n.type as NodeLabel,
      description: n.label,
      ...Object.fromEntries(
        Object.entries(n).filter(([k]) => !['id', 'label', 'type'].includes(k)),
      ),
    },
  })),
  edges: tech_tree.edges.flatMap((e) => {
    if (e.target) {
      return [
        {
          id: e.id,
          source: e.source,
          target: e.target,
        },
      ];
    }
    if (e.targets) {
      return e.targets.map((t, idx) => ({
        id: `${e.id}_${idx}`,
        source: e.source,
        target: t,
      }));
    }
    return [];
  }),
};
